all: method1 method2 method3
method1:
	echo "Method 1"
	rm -f bin/*_method1.txt img/method1.png
	g++ method1.cpp -o method1
	./method1
	rm method1

method2:
	echo "Method 2"
	rm -f bin/*_method2.txt img/method2.png
	g++ method2.cpp -o method2
	./method2
	rm method2

method3:
	echo "Method 3"
	rm -f bin/*_method3.txt img/method3.png
	g++ method3.cpp -o method3
	./method3
	rm method3